cosmostation/cosmostation-android

- app/src/main/java/wannabit/io/cosmostaion/activities/WalletConnectActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/chains/starname/StarNameWalletConnectActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
Android - binance wallet connect bug fix
> [ANDWL] - File External Storage dir change

- app/src/main/java/wannabit/io/cosmostaion/activities/MainActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/VoteDetailsActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/VoteListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainHistoryFragment.java
- app/src/main/java/wannabit/io/cosmostaion/network/ApiClient.java
- app/src/main/java/wannabit/io/cosmostaion/network/Station.java
- app/src/main/java/wannabit/io/cosmostaion/network/res/ResProposal.java
- app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/MintScanProposalTask.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
- app/src/main/res/values/strings.xml
Android - proposal detail upgrade
> [ANDWL-73] api init for proposal detail

- app/src/main/java/wannabit/io/cosmostaion/fragment/SendStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
Android - okex address check bug fix
> [ANDWL] valid check for Okex bug fix

- app/src/main/java/wannabit/io/cosmostaion/activities/MainActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseData.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainTokensFragment.java
Android - okex url change for account
> [ANDWL] url change for okex

- app/build.gradle
- app/src/main/java/wannabit/io/cosmostaion/base/BaseApplication.java
- gradle.properties
configure build setting for build speed
> [ANDWL-85] Build config

- app/src/main/java/wannabit/io/cosmostaion/base/BaseChain.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
- app/src/main/java/wannabit/io/cosmostaion/network/ChannelBuilder.java
- app/src/main/java/wannabit/io/cosmostaion/network/res/ResApiNewTxListCustom.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java
- app/src/main/res/layout/dialog_choice_net.xml
- app/src/main/res/layout/item_wallet_grabridge.xml
- app/src/main/res/values/strings.xml
Android - gravity-bridge Chain init
> [ANDWL] prepare gravity-bridge chain

- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
Android - chain id by chain type fixed
> [ANDWL] Chain Id by Chain Type

- app/src/main/java/wannabit/io/cosmostaion/activities/HtlcResultActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/HtlcSendActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/TxDetailgRPCActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/HtlcSendStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/network/res/ResApiNewTxListCustom.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/broadcast/KavaClaimHTLCGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/broadcast/KavaCreateHTLCGrpcTask.java
> [ANDWL] histroy grpc data init

- app/src/main/java/wannabit/io/cosmostaion/base/BaseData.java
> [ANDWL] update custom path refact for 2 type path chains

- app/src/main/java/wannabit/io/cosmostaion/dao/ChainParam.java
> [ANDWL-145] provision crashed bug fixed

- app/src/main/java/wannabit/io/cosmostaion/fragment/MainTokensFragment.java
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/strings.xml
Android - naming update with OKC
> [ANDWL-189] update naming OEC -> OKC

- app/src/main/java/wannabit/io/cosmostaion/activities/ConnectWalletActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/HtlcResultActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/MnemonicCheckActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/TxDetailgRPCActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/chains/nft/NFTListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/DelegateStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/HtlcSendStep2Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/ReInvestStep3Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/RewardStep3Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/SendStep1Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/chains/kava/ListHardFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/chains/ok/OKStakingFragmentStep0.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/chains/starname/MyAccountFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/chains/starname/MyDomainFragment.java
The first test of the dialog has been completed. I will keep checking. thank you.
> [ANDWL-190] dialog-test

- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
Android - Change gas rate with Cudos
> [ANDWL-235] Change gas rate with Cudos

- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
- app/src/main/res/values-ko/strings.xml
> Andwl 235 upgrade cudos gas rate

- app/src/main/java/wannabit/io/cosmostaion/activities/setting/WalletDeriveActivity.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/Dialog_IBC_Receivable_Accouts.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/Dialog_WC_Account.java
- app/src/main/res/layout/activity_wallet_derive.xml
> [ANDWL-106] add init & lastTotal bug fixed

- app/src/main/java/wannabit/io/cosmostaion/activities/MainActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainHistoryFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSendFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSettingFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainTokensFragment.java
move menu fragment to activity
> [ANDWL-239] refactoring main menu

- app/src/main/java/wannabit/io/cosmostaion/activities/AccountDetailActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/MainActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/BridgeTokenGrpcActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/ContractTokenGrpcActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/IBCTokenDetailActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/NativeTokenGrpcActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/StakingTokenGrpcActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/ClaimRewardActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/ReInvestActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/RewardAddressChangeActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/kava/DAppsList5Activity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/osmosis/EarningDetailActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/osmosis/LabsListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/sif/SifDexListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/ReInvestStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/ReInvestStep3Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/RewardAddressChangeStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/RewardAddressChangeStep3Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/RewardStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/RewardStep3Fragment.java
- app/src/main/res/layout/fragment_reinvest_step0.xml
- app/src/main/res/layout/fragment_reinvest_step3.xml
- app/src/main/res/layout/fragment_reward_address_change_step0.xml
- app/src/main/res/layout/fragment_reward_address_change_step3.xml
- app/src/main/res/layout/fragment_reward_step0.xml
- app/src/main/res/layout/fragment_reward_step3.xml
- app/src/main/res/layout/fragment_send_step0.xml
Android. -Chainconfig init with distribution tx
> [ANDWL-239] chainconfig init with distribution tx

- app/src/main/java/wannabit/io/cosmostaion/dao/ChainParam.java
Android - update with stargaze apr
> [ANDWL-248] Change with stargaze apr

- app/src/main/java/wannabit/io/cosmostaion/activities/setting/PrivateKeyCheckActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/NFTokenDetailActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/RedelegateStep1Fragment.java
- app/src/main/res/layout/activity_private_key_check.xml
- app/src/main/res/layout/fragment_htlc_send_step0.xml
- app/src/main/res/layout/fragment_ibc_send_step0.xml
- app/src/main/res/layout/fragment_tx_step_fee_grpc.xml
- app/src/main/res/layout/item_redelegate_validator.xml
- iris, crypto nft send bug fix
- send, delegate tx fee btn clickable(false)
- redelegate border color change
- move mainsettingfragment after checking privatekey
> [ANDWL-262] android bug fix

- app/src/main/java/wannabit/io/cosmostaion/base/chains/Evmos.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/FetchAi.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/GravityBridge.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Injective.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Juno.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Stargaze.java
Android - Authz Support Chain init
> [ANDWL-218] authz support chain init

- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
- app/src/main/java/wannabit/io/cosmostaion/widget/authz/AuthzExecuteInfoHolder.java
- app/src/main/res/layout/item_authz_execute_info.xml
- app/src/main/res/layout/item_authz_granter_list.xml
- app/src/main/res/layout/item_chain_account.xml
- app/src/main/res/values/dimens.xml
> [ANDWL-218] authz design fixed

- app/src/main/java/wannabit/io/cosmostaion/activities/setting/PrivateKeyCheckActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/NFTokenDetailActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/RedelegateStep1Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
- app/src/main/res/drawable-night/dialog_bg_colorwhite2daynight.xml
- app/src/main/res/drawable/dialog_bg.xml
- app/src/main/res/drawable/dialog_bg_colorwhite2daynight.xml
- app/src/main/res/layout/activity_private_key_check.xml
- app/src/main/res/layout/dialog_change_nickname.xml
- app/src/main/res/layout/dialog_template_choice.xml
- app/src/main/res/layout/dialog_template_recycler.xml
- app/src/main/res/layout/fragment_htlc_send_step0.xml
- app/src/main/res/layout/fragment_ibc_send_step0.xml
- app/src/main/res/layout/fragment_tx_step_fee_grpc.xml
- app/src/main/res/layout/item_redelegate_validator.xml
- ibc token null check add
- dialog border design change
- mnemonics delete bug fix
> [ANDWL-262] bug fix last

- app/src/main/res/layout/item_new_history.xml
- app/src/main/res/layout/item_reward_all_info.xml
Android - easymode title init & padding update
> [ANDWL-263] title init & padding update

- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSettingFragment.java
- app/src/main/res/layout/fragment_main_setting.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/strings.xml
Android - Blog url init with cosmostation blog
> [ANDWL-260] blog url init

- app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorListActivity.java
> [ANDWL-263] easy mode bug fixed

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/authz/AuthzClaimCommissionActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/authz/AuthzClaimRewardActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/authz/AuthzDelegateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/authz/AuthzRedelegateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/authz/AuthzSendActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/authz/AuthzUndelegateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/authz/AuthzVoteActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/ClaimRewardActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/DelegateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/IBCSendActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/ReInvestActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/RedelegateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/RewardAddressChangeActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/SendActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/UndelegateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/VoteActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java
- app/src/main/java/wannabit/io/cosmostaion/cosmos/Signer.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepMemoFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/authz/AuthzClaimCommissionStep3Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/network/res/ResApiNewTxListCustom.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/broadcast/AuthzVoteGrpcTask.java
- app/src/main/res/layout/item_reward_all_info.xml
- app/src/main/res/layout/item_segmented_fee.xml
Android - Auth Tx init with Common, Authz Tx
> [ANDWL-250] auto tx init with common, authz

- app/src/main/java/wannabit/io/cosmostaion/base/chains/Crytoorg.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Iris.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
Android - QA bug fixed(iris, cryto nft && provenance gas amount)
> [ANDWL-269] iris, cryto.org nft gone, provenance gas amount bug fixed

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/kava/HtlcSendActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/ok/OKStakingFragmentStep0.java
- app/src/main/java/wannabit/io/cosmostaion/widget/mainWallet/WalletOkexHolder.java
Android - BaseConstant Gas Delete
> [ANDWL-272] BaseConstant gas delete

- app/src/main/java/wannabit/io/cosmostaion/dialog/CommonAlertDialog.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/FilledVerticalButtonAlertDialog.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/PaddedVerticalButtonAlertDialog.java
- app/src/main/res/layout/dialog_template_filledvertical.xml
> [ANDWL-270] issue fix

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/VoteListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/authz/AuthzVoteStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/authz/AuthzVoteStep1Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/VoteStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java
- app/src/main/java/wannabit/io/cosmostaion/widget/tokenDetail/UnBondingHolder.java
- app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/osmosis/TxBeginUnlockTokenHolder.java
Android - Common data init with date to long
> [ANDWL-272] common init with date to long

- app/src/main/java/wannabit/io/cosmostaion/widget/tokenDetail/TokenStakingNewHolder.java
- app/src/main/java/wannabit/io/cosmostaion/widget/tokenDetail/UnBondingHolder.java
Android - ChainBgColor init bug fixed
> [ANDWL-272] chain bg color bug fixed

- app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/kava/ListKavaSwapFragment.java
- NPE check
- unused import delete, formatter apply
> [ANDWL-271] abnormal-end-bug-fix

- app/src/main/java/wannabit/io/cosmostaion/dialog/Dialog_Wc_Raw_Data.java
> [ANDWL-282] build bug fix

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/wc/ConnectWalletActivity.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/Dialog_Wc_Raw_Data_Evmos.java
- ethsign, ethsendtx method change
- evmos dialogfragment change
> [ANDWL-257] dapp dialog method change

- app/src/main/java/wannabit/io/cosmostaion/dialog/Dialog_Wc_Account.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/HtlcReceivableAccountsDialog.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/HtlcSendCoinDialog.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/IBCReceiveAccountsDialog.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/IBCReceiveChainDialog.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/IBCRelayerChannelDialog.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/StarnameDomainDialog.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/SwapCoinListDialog.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/WalletStarnameDialog.java
- app/src/main/res/layout/dialog_template_recycler.xml
- app/src/main/res/layout/item_dialog_account.xml
- app/src/main/res/layout/item_dialog_receive_chian.xml
- alertdialog builder delete
- linearlayout convert to constraintlayout
> [ANDWL-282] recyclerview dialog improve

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/SendActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSettingFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepMemoFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/SendStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java
- app/src/main/res/layout/fragment_tx_step_memo.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/strings.xml
Android - Except init exchange Address with send memo, ibc send
> [ANDWL-288] except init exchange address with send, ibc send

- app/src/main/java/wannabit/io/cosmostaion/base/BaseData.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainTokensFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/SendStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
> [ANDWL-277] asset v2 bug fixed

- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
Android - Insufficient amount coment init
> [ANDWL-302] Toast tx fee Insufficient amount coment init

- app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorListActivity.java
Android - Auto pass init with One Click Tx
> [ANDWL-304] auto pass init with one click tx

- app/src/main/java/wannabit/io/cosmostaion/dao/ChainParam.java
Android - Axelar Inflation init
> [ANDWL-305] inflation hard cording with axelar

- app/src/main/java/wannabit/io/cosmostaion/activities/setting/WalletDeriveActivity.java
* dialog cancel button bug fix
> [ANDWL-291] derive wallet improve bug fix

- app/src/main/res/layout/fragment_send_step0.xml
- button margin, background change
> send-background-change

- app/src/main/java/wannabit/io/cosmostaion/dao/ChainParam.java
> [ANDWL-307] Axelar Apr updated

- app/src/main/java/wannabit/io/cosmostaion/activities/AccountDetailActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/MainActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/setting/MnemonicCreateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/setting/MnemonicListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/setting/MnemonicRestoreActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/setting/PrivateKeyRestoreActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/setting/WatchingWalletAddActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/starname/StarNameResourceAddActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/wc/ConnectWalletActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSettingFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepMemoFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/authz/AuthzSendStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/RewardAddressChangeStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/SendStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/nft/NFTSendStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/starname/RegisterAccount1Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/starname/ReplaceStarName0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/widget/mainWallet/WalletBinanceHolder.java
- app/src/main/java/wannabit/io/cosmostaion/widget/mainWallet/WalletChainHolder.java
> [ANDWL-223] deprecated update

- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/starname/RegisterDomain0Fragment.java
- app/src/main/res/values/styles.xml
- switch background color change
- string value method change
> [ANDWL-309] switch background color change

- app/src/main/java/wannabit/io/cosmostaion/base/chains/Bitcanna.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Cerberus.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Chihuahua.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Ki.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Lum.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Persistence.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Rizon.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Sif.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Umee.java
> [ANDWL-313] support authz chain

- app/src/main/java/wannabit/io/cosmostaion/dialog/SelectChainListDialog.java
- app/src/main/res/layout/item_pool_list_my.xml
- app/src/main/res/layout/item_pool_list_other.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/strings.xml
> [ANDWL-314] watching wallet add bug fix

- app/src/main/java/wannabit/io/cosmostaion/activities/setting/WalletDeriveActivity.java
- app/src/main/res/layout/fragment_main_setting.xml
- searchbar setquery clear
- bio button clickable delete
> [ANDWL-291] searchbar setquery clear

- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/strings.xml
> [ANDWL-323] translate support

- app/src/main/java/wannabit/io/cosmostaion/base/chains/Chihuahua.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Injective.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Ki.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Stargaze.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Stride.java
- app/src/main/java/wannabit/io/cosmostaion/widget/mainWallet/WalletChainHolder.java
- ki, chihuahua, stride, stargaze, injective support
> [ANDWL-333] wallet connect button add

- app/src/main/java/wannabit/io/cosmostaion/dao/Param.java
Inflation & Apr init with Stride
> [ANDWL-330] inflation & Apr init with stride

- app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/MintScanUtilityParamTask.java
Api ChainName Hardcording with crypto-org, ki-chain
> [ANDWL-329] utility api init with ki, crypto

- app/src/main/res/layout/item_earn_validator.xml
> [ANDWL-318] qa test

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/VoteDetailsActivity.java
- app/src/main/java/wannabit/io/cosmostaion/network/res/ResProposal.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
- app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/kava/TxLiquidityHolder.java
- app/src/main/res/layout/item_vote_info.xml
QA Bug fixed
- base param null check
- kava earn tx detail except
- vote detail bug fixed
> [ANDWL-338] QA bug fixed

- app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
- app/src/main/res/layout/fragment_send_step0.xml
- app/src/main/res/layout/fragment_send_step4.xml
- app/src/main/res/layout/item_ok_validator.xml
- app/src/main/res/layout/item_wallet_price.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/font.xml
- app/src/main/res/values/strings.xml
> [ANDWL-339] android issue fix

- app/src/main/java/wannabit/io/cosmostaion/dao/Asset.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/SendStep0Fragment.java
Crypto Send Chain List Bug fixed (Stride delete)
> [ANDWL-605] chain list bug fixed

- app/src/main/res/layout/fragment_claim_incentive_0.xml
- app/src/main/res/layout/fragment_claim_incentive_3.xml
- app/src/main/res/layout/fragment_swap_step0.xml
- kava swap button overlap view fix
> [APP-601] kava design issue

- app/src/main/java/wannabit/io/cosmostaion/base/BaseChain.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Akash.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Comdex.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Cosmos.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Crescent.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Kava.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Konstellation.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Medibloc.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Nyx.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Omniflix.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Passage.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Persistence.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Regen.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Secret.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Shentu.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSendFragment.java
> [ANDWL-609] Add Authz support chain

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/authz/AuthzDetailActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseData.java
- app/src/main/java/wannabit/io/cosmostaion/dao/Asset.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/SendStep0Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/txs/common/SendStep1Fragment.java
- app/src/main/java/wannabit/io/cosmostaion/network/res/ResApiNewTxListCustom.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java
> [ANDWL-554] code rollback & code refact

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/kava/DAppsList5Activity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/liquidstaking/StrideLSActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/starname/StarNameListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSendFragment.java
- app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java
Mode Change app crashed bug fixed
> [App-632] design mode change with crash bug fixed

- app/src/main/java/wannabit/io/cosmostaion/model/type/Msg.java
- app/src/main/java/wannabit/io/cosmostaion/network/res/ResApiNewTxListCustom.java
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/strings.xml
Vote Tx Error bug fixed with Kava Wallet Connect & Dapp
> [App-647] vote msg tx error bug fixed & history type add

- app/src/main/java/wannabit/io/cosmostaion/activities/MainActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/wc/BnbWalletConnectActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSettingFragment.java
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/strings.xml
Wc bug fixed with binance, starname
> [App-659] wc url bug fixed with binance, starname

- app/src/main/java/wannabit/io/cosmostaion/base/chains/Band.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Desmos.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Iris.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Ixo.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Provenance.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Quicksilver.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Starname.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSendFragment.java
- app/src/main/res/layout/item_wallet_authz.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/strings.xml
> [App-664] Support new authz chain

- app/src/main/java/wannabit/io/cosmostaion/base/chains/Binance.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Okc.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/SelectCWTokenDialog.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainTokensFragment.java
- app/src/main/res/drawable-night/box_round_vote.xml
- app/src/main/res/drawable/box_round_vote.xml
- app/src/main/res/layout/dialog_select_display_token.xml
- app/src/main/res/layout/fragment_delegate_step0.xml
- app/src/main/res/layout/fragment_delegate_step3.xml
- app/src/main/res/layout/fragment_tx_step_memo.xml
- app/src/main/res/layout/fragment_vote_step3.xml
- app/src/main/res/layout/item_account_list.xml
- app/src/main/res/layout/item_edit.xml
- app/src/main/res/layout/item_proposal.xml
- app/src/main/res/layout/item_proposal_selection.xml
- app/src/main/res/layout/item_validator_my_action.xml
- app/src/main/res/layout/item_vote_info.xml
- app/src/main/res/layout/item_vote_tally.xml
- app/src/main/res/layout/item_wallet_price.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
> [APP-665] ui fix

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/VoteDetailsActivity.java
> [APP-668] vote detail fix

- app/src/main/java/wannabit/io/cosmostaion/activities/MainActivity.java
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values/strings.xml
Add OKC deprecated path key warn msg
> [App-669] Add OKC deprecated path key warn msg

- app/src/main/java/wannabit/io/cosmostaion/dao/Param.java
- app/src/main/java/wannabit/io/cosmostaion/network/Station.java
- param url change
- null check
> [APP-670] chain param url change

- app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/ClaimRewardActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/DelegateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/ReInvestActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/RedelegateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/RewardAddressChangeActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/SendActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/UndelegateActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/common/VoteActivity.java
- app/src/main/java/wannabit/io/cosmostaion/activities/txs/osmosis/SwapActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/ChainFactory.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSettingFragment.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
- app/src/main/java/wannabit/io/cosmostaion/utils/LedgerManager.kt
> [APP] Ledger code refact with sign

- app/build.gradle
https://github.com/cosmostation/hw-transport-android-ble/commit/6e9b7119fd1906558cd93dfc5b7ddf80979b0169
> [APP-733] ledger bug fix

- app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorListActivity.java
- app/src/main/java/wannabit/io/cosmostaion/cosmos/Signer.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulChangeRewardAddressGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulClaimRewardsGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulDelegateGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulIBCTransferGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulOsmosisSwaplnGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulReInvestGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulRedelegateGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulSendGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulUndelegateGrpcTask.java
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/simulate/SimulVoteGrpcTask.java
> [APP-741] simul bug fixed

- app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/StakingTokenGrpcActivity.java
- app/src/main/java/wannabit/io/cosmostaion/fragment/MainSendFragment.java
- app/src/main/java/wannabit/io/cosmostaion/widget/mainWallet/WalletNeutronHolder.kt
- app/src/main/java/wannabit/io/cosmostaion/widget/mainWallet/WalletNobleHolder.kt
- app/src/main/java/wannabit/io/cosmostaion/widget/tokenDetail/TokenDetailHolder.java
- app/src/main/res/layout/item_amount_detail.xml
- app/src/main/res/layout/item_wallet_noble.xml
> [APP-757] Update noble custom

- app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/StakingTokenGrpcActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
- app/src/main/java/wannabit/io/cosmostaion/base/BaseData.java
- app/src/main/java/wannabit/io/cosmostaion/network/req/neutron/ReqVestingData.kt
- app/src/main/java/wannabit/io/cosmostaion/network/res/neutron/ResVestingData.kt
- app/src/main/java/wannabit/io/cosmostaion/task/gRpcTask/VestingGrpcTask.kt
- app/src/main/java/wannabit/io/cosmostaion/widget/mainWallet/WalletNeutronHolder.kt
- app/src/main/java/wannabit/io/cosmostaion/widget/tokenDetail/TokenDetailHolder.java
- app/src/main/java/wannabit/io/cosmostaion/widget/tokenDetail/VestingHolder.java
- app/src/main/res/layout/item_wallet_neutron.xml
- app/src/main/res/layout/layout_card_neutron.xml
> [APP-773] vesting init with neutron

- app/src/main/java/wannabit/io/cosmostaion/dao/Param.java
> [APP-785] Update Archway Apr

- app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java
> [APP-786] Update gas with Chihuahua

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/wc/WalletConnectActivity.kt
- app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
- app/src/main/java/wannabit/io/cosmostaion/cosmos/MsgGenerator.java
- app/src/main/java/wannabit/io/cosmostaion/dialog/DappSignDialog.kt
- app/src/main/java/wannabit/io/cosmostaion/model/WcSignModel.java
Support injective dapp with astroport
> [APP-788] support injective dapp with astroport

- app/src/main/java/wannabit/io/cosmostaion/activities/txs/wc/WalletConnectActivity.kt
> fix keplr dapp bug

- app/src/main/java/wannabit/io/cosmostaion/base/BaseChain.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Konstellation.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Kujira.java
- app/src/main/java/wannabit/io/cosmostaion/base/chains/Sif.java
- app/src/main/res/values/strings.xml
Update api url & chain terminate(konstell, kujira, sif)
> [APP-800] Update api url & chain terminate(konstell, kujira, sif)

- app/src/main/java/wannabit/io/cosmostaion/dao/Param.java
> [APP-809] update axelar inflation & apr

- app/src/main/java/wannabit/io/cosmostaion/base/chains/Crytoorg.java
- app/src/main/res/values/strings.xml
> [APP-810] Update chain with cronos pos

- app/src/main/java/wannabit/io/cosmostaion/ui/tx/TransferTxResultActivity.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/tx/TxResultActivity.kt
- app/src/main/res/layout/activity_tx_result.xml
Display tx hash with tx result
> [APP-907] display tx hash with tx result

- app/src/main/java/wannabit/io/cosmostaion/data/model/res/Proposal.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/tx/step/VoteAdapter.kt
Add crash guard code for proposal parsing
> [APP-904] Add crash guard code for proposal parsing

- app/src/main/java/wannabit/io/cosmostaion/ui/option/tx/swap/AssetSelectAdapter.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/option/tx/swap/AssetSelectFragment.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/option/tx/swap/AssetSelectViewHolder.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/tx/TxResultActivity.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/tx/step/SwapFragment.kt
> [APP-906] Display token amount with 0

- app/src/main/AndroidManifest.xml
- app/src/main/java/wannabit/io/cosmostaion/ui/main/DashboardFragment.kt
- app/src/main/res/drawable/search_bg.xml
- app/src/main/res/layout/fragment_dashboard.xml
- app/src/main/res/layout/item_chain_manage.xml
- app/src/main/res/values/colors.xml
> [APP-912] search bar init with dashboard

- app/src/main/java/wannabit/io/cosmostaion/chain/BaseChain.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/CosmosLine.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/EthereumLine.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/cosmosClass/ChainBinanceBeacon.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/cosmosClass/ChainOkt996Keccak.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainAltheaEvm.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainBaseEvm.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainCantoEvm.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainDymensionEvm.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainEthereum.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainEvmosEvm.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainHumansEvm.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainKavaEvm.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainOktEvm.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainOptimism.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainPolygon.kt
- app/src/main/java/wannabit/io/cosmostaion/chain/evmClass/ChainXplaEvm.kt
- app/src/main/java/wannabit/io/cosmostaion/common/Extensions.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/main/chain/cosmos/CosmosDetailFragment.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/main/chain/cosmos/HistoryAdapter.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/main/chain/cosmos/HistoryViewHolder.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/main/chain/evm/EvmDetailFragment.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/main/chain/evm/EvmHistoryFragment.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/tx/TransferTxResultActivity.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/tx/info/ProposalListViewHolder.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/tx/step/service/AllChainAllVoteViewHolder.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/tx/step/service/AllChainNotVoteViewHolder.kt
> [APP-934] explorer data init with param

- app/src/main/java/wannabit/io/cosmostaion/database/model/BaseAccount.kt
- app/src/main/java/wannabit/io/cosmostaion/ui/main/dapp/DappActivity.kt
> [APP-1075] init data thread with dapp

- proto/src/main/java/com/desmos/profiles/v3/MsgsDtagRequestsProto.java
requet → request
requets → requests
> fix typos in MsgsDtagRequestsProto.java
